name: ci-golang-workflow
#Evento
on: [push]
jobs:
  checks-application:
    runs-on: ubuntu-latest
    # Steps: Definem o conjuntos de ações e comandos para rodar no ambiente
      # Actions: são aplicações a serem rodadas em repositórios do próprio github
        # https://github.com/actions/checkout
        # Actions são definidas usando palavra reservada 'uses'
      # Comandos: Comandos a serem rodados no ambiente
        # Comandos são definidas usando palavra reservada 'run'
    steps:
      # Faz checkout da aplicação no ubuntu
      - uses: actions/checkout@v2
      # Prepara o ambiente go no ubuntu
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run main.go